### ISSUE TITLE
Getting warnings

### ISSUE THREAD

**Issue by wyamout** [Widdin/wp-bricks-elements#2]
Thanks for this. Getting some warnings.

Warning: Attempt to read property "term_id" on array in /public_html/wp-content/plugins/wp-bricks-elements-main/elements/gallery-filter/gallery-filter.php on line 276

Warning: Attempt to read property "name" on array in /public_html/wp-content/plugins/wp-bricks-elements-main/elements/gallery-filter/gallery-filter.php on line 276

Warning: Attempt to read property "term_id" on array in/public_html/wp-content/plugins/wp-bricks-elements-main/elements/gallery-filter/gallery-filter.php on line 276

Warning: Attempt to read property "name" on array in /public_html/wp-content/plugins/wp-bricks-elements-main/elements/gallery-filter/gallery-filter.php on line 276

Is there any way we can use this for archive templates where the filters are the subcategories.

**Comment by Widdin** [comment]
Warnings solved in https://github.com/Widdin/wp-bricks-elements/pull/4 😊
